# Nonparametric Estimation of Threshold Exceedance Probability

In [16]:
import numpy as np
import pandas as pd

from scipy.special import gamma

Assume that $\left\{ X(s): s \in D \subset \mathbb R^d \right\}$. For fixed $x_0 \in \mathbb R$  we define the exceedance probability at location $s$ as 

$$
P_{x_0} (s) = P\left[ X(s) \geq x_0 \right]
$$

we define an estimator as

$$
\hat P_{x_0} (s) = \frac{
\sum_{i=1}^n K \left(\frac{s_i - s}{h}\right) \pmb 1_{ \left\{X(s) \geq x_0\right\}} 
}{
\sum_{i=1}^n K \left(\frac{s_i - s}{h}\right)
}
$$

where $h$ represents a bandwidth parameter and $K: \mathbb R^d \to \mathbb R$ is a kernel function.

Example:

Epanechnikov Kernel:

$$
K(u) = \frac{3}{4} \left( 1 - u^2 \right), \qquad |u| \leq 1
$$

In [23]:
d = 2
epanechnikov_cte_2d = gamma(2 + d / 2) / (np.pi ** (d / 2))

In [24]:
def epanechnikov(u, cte=epanechnikov_cte_2d):
    u_norm = np.linalg.norm(u)
    if u_norm <= 1:
        return epanechnikov_cte_2d * (1 - u_norm ** 2) 
    else:
        return 0.0

In [25]:
print(epanechnikov(0.5))
print(epanechnikov(2))
print(epanechnikov(np.array([0.0, 0.1, 1., 2.])))

0.477464829275686
0.0
0.0


In [34]:
x = np.array(
    [
        [0.1, 0.2],
        [1.0, 2.0],
        [0.0, 0.0]
    ]
)

In [40]:
np.apply_along_axis(epanechnikov, 1, x) 

array([0.60478878, 0.        , 0.63661977])

Create a mesh

In [51]:
x_max = 1
y_max = 1
nx, ny = (6, 6)
x = np.linspace(0, x_max, nx)
y = np.linspace(0, y_max, ny)
xv, yv = np.meshgrid(x, y)
xv

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. ]])

In [58]:
yv

array([[0. , 0. , 0. , 0. , 0. , 0. ],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.6, 0.6, 0.6, 0.6, 0.6, 0.6],
       [0.8, 0.8, 0.8, 0.8, 0.8, 0.8],
       [1. , 1. , 1. , 1. , 1. , 1. ]])

In [75]:
S = np.stack((xv.ravel(), yv.ravel()), axis=1)
S.shape

(36, 2)

In [77]:
s_est = np.array([0.2, 0.4]) 

In [78]:
(S - s_est).shape

(36, 2)

In [79]:
h = 0.01

In [83]:
np.apply_along_axis(epanechnikov, 1, (S - s_est) / h) 

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.63661977, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])