# Simulación Estocástica
## Tarea N01

Alonso Ogueda Oliva

Escriba una rutina para resolver el sistema de ecuaciones lineales $\mathbf{Ax} = \mathbf{b}$ con:

$$\mathbf{A} = \begin{pmatrix}
1 & 1 & 1 \\
2 & 3 & 1 \\
1 & -1 & -1 \\
\end{pmatrix}
,  \qquad
\mathbf{b} = \begin{pmatrix}
4 \\
9 \\
-1
\end{pmatrix}
$$
usando la **descomposición LU** y **refinamiento iterativo.**

In [35]:
import numpy as np
import scipy.linalg as la

In [10]:
A = np.array([
    [1., 1., 1.],
    [2., 3., 1.],
    [1., -1., -1.]
])

b = np.array([4, 9, -1])

In [8]:
np.linalg.det(A)

-4.000000000000001

Se define el sistema lineal 
$$ \mathbf{Ax} = \mathbf{LUx} = b$$

Resolviendo el sistema triangular $\mathbf{Lz} = b$ se obtiene que 

In [51]:
(P, L, U) = la.lu(A)

In [47]:
P

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [52]:
L

array([[1. , 0. , 0. ],
       [0.5, 1. , 0. ],
       [0.5, 0.2, 1. ]])

In [53]:
U

array([[ 2. ,  3. ,  1. ],
       [ 0. , -2.5, -1.5],
       [ 0. ,  0. ,  0.8]])

In [48]:
P @ L @ U 

array([[ 1.,  1.,  1.],
       [ 2.,  3.,  1.],
       [ 1., -1., -1.]])

In [32]:
def backward_substitution(T, b):
    T = T.astype(float)
    n = T.shape[0]
    x = np.zeros(n)
    x[n - 1] = b[n - 1] / T[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = (b[i] - T[i, i + 1] * x[i + 1]) / T[i, i]
    return x

In [33]:
backward_substitution(A, b)

array([1.33333333, 2.66666667, 1.        ])

I Implementar el operador Sweep usando su lenguaje de programaci´on favorito.

I Pruebe su rutina para obtener la inversa de una matriz usando el operador
Sweep con la siguiente matriz:
B = 0 @30 16 46 16 10 26 46 26 721 A :

I Verifique que B es matriz semidefinida positiva usando la factorizaci´on
Cholesky. >En cu´al etapa del algoritmo el procedimiento falla?